vim.opt.shell = "/bin/bash"

require('core/basic')
require('packer_init')
require('plugins/ui')
require('plugins/nvim_tree')
require('plugins/nvim_lspconfig')
require('plugins/nvim_cmp')
require('plugins/vim_fugitive')
require('plugins/blamer')
require('plugins/tagbar')
require('plugins/lualine')
require('plugins/nvim_treesitter')
require('plugins/telescope')
require('plugins/nvim_dap')
